name: Unit Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test with ceedling
      run: |
        docker run \
        -v $(pwd):/project -i throwtheswitch/madsciencelab:latest ceedling test:all gcov:all utils:gcov
    - uses: actions/upload-artifact@v2
      with:
        name: ceedlingReport
        path: build
    - name: Upload coverage Report
      uses: codecov/codecov-action@v1.5.0
      with:
        token: ${{ secrets.CODECOV_TOKEN}}
        files: ./build/artifacts/gcov/report_cobertura.xml
        flags: unittests
        
